# Generated by Django 4.2.1 on 2023-06-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertificats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(max_length=32, verbose_name='Вид сертификата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.CharField(max_length=5, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ('view',),
            },
        ),
        migrations.AlterModelOptions(
            name='massage',
            options={'ordering': ('name',), 'verbose_name': 'Массаж', 'verbose_name_plural': 'Массажи'},
        ),
    ]
