# Generated by Django 4.2.1 on 2023-06-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sertificats_alter_massage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='банк')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='massage',
            options={'ordering': ['id'], 'verbose_name': 'Массаж', 'verbose_name_plural': 'Массажи'},
        ),
        migrations.AlterModelOptions(
            name='sertificats',
            options={'ordering': ['id'], 'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификаты'},
        ),
    ]
