# Generated by Django 4.2.1 on 2023-06-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Ваше имя:')),
                ('text', models.TextField(verbose_name='Текст отзыва:')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('status', models.BooleanField(default=False, verbose_name='Видимость статьи')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id'], 'verbose_name': 'Доп услуга', 'verbose_name_plural': 'Доп услуги'},
        ),
    ]
