# Generated by Django 4.2.1 on 2023-06-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comments_alter_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='%Y/%m/%d', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Картинка для пользователей',
            },
        ),
    ]
