# Generated by Django 4.2.1 on 2023-06-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_stop_delete_userimage_alter_comments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='text',
            field=models.TextField(max_length=800, verbose_name='Список противопоказаний:'),
        ),
    ]
